# Generated by Django 2.1.7 on 2019-03-23 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
