# Generated by Django 2.1.7 on 2019-03-24 01:55

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_session_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date_created',
        ),
        migrations.AddField(
            model_name='session',
            name='date_time',
            field=users.models.UnixTimestampField(auto_created=True, null=True),
        ),
    ]
