# Generated by Django 2.1.7 on 2019-03-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190324_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='date_time',
            new_name='date_created',
        ),
    ]
