# Generated by Django 2.1.7 on 2019-03-24 01:58

from django.db import migrations
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190324_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_created',
            field=users.models.UnixTimestampField(default=django.utils.timezone.now, null=True),
        ),
    ]
