# Generated by Django 2.1.7 on 2019-03-24 02:00

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190324_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_created',
            field=users.models.UnixTimestampField(auto_created=True, null=True),
        ),
    ]
