# Generated by Django 2.1.7 on 2019-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190324_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='right_ans',
            field=models.CharField(choices=[('First', 'First'), ('Last', 'Last')], default='Last', max_length=10),
        ),
    ]
