# Generated by Django 2.1.7 on 2019-03-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_right_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='right_ans',
            new_name='valid_ans',
        ),
    ]
