# Generated by Django 2.1.7 on 2019-05-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_auto_20190502_1615'),
        ('users', '0011_auto_20190324_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
