# Generated by Django 2.1.7 on 2019-03-09 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('ansA', models.CharField(max_length=100)),
                ('ansB', models.CharField(max_length=100)),
                ('ansC', models.CharField(max_length=100)),
                ('ansD', models.CharField(max_length=100)),
                ('ansE', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default_profile_pic.jpg', upload_to='quiz_img')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
