# Generated by Django 2.1.7 on 2019-03-16 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('ansA', models.CharField(max_length=50)),
                ('ansB', models.CharField(max_length=50)),
                ('ansC', models.CharField(max_length=50)),
                ('ansD', models.CharField(max_length=50)),
                ('ansE', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='no_image.jpg', upload_to='quiz_img')),
                ('right_ans', models.CharField(choices=[('A', 'a)'), ('B', 'b)'), ('C', 'c)'), ('D', 'd)'), ('E', 'e)')], default='A', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
