# Generated by Django 2.1.7 on 2019-03-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190310_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='ansA',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ansB',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ansC',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ansD',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ansE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='quiz_img'),
        ),
    ]
