# Generated by Django 2.1.7 on 2019-03-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190314_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='right_ans',
            field=models.CharField(choices=[('A', 'a)'), ('B', 'b)'), ('C', 'c)'), ('D', 'd)'), ('E', 'e)')], default='A', max_length=1),
        ),
    ]
