# Generated by Django 2.1.7 on 2019-03-15 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='execution_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
