# Generated by Django 2.1.7 on 2019-03-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190315_1851'),
        ('quiz', '0006_quiz_execution_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ManyToManyField(to='users.Course'),
        ),
    ]
