# Generated by Django 2.1.7 on 2019-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20190320_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='date_time',
        ),
        migrations.AddField(
            model_name='results',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
