# Generated by Django 2.1.7 on 2019-03-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_results_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
