# Generated by Django 2.1.7 on 2019-03-23 14:21

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190322_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerProcessing',
            fields=[
                ('date_time', quiz.models.UnixTimestampField(auto_created=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nmec', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=100)),
            ],
        ),
    ]
