# Generated by Django 2.1.7 on 2019-03-23 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_answerprocessing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerprocessing',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
