# Generated by Django 2.1.7 on 2019-03-23 14:51

from django.db import migrations
import django.utils.timezone
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20190323_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=quiz.models.UnixTimestampField(default=django.utils.timezone.now, null=True),
        ),
    ]
