# Generated by Django 2.1.7 on 2019-03-23 15:13

from django.db import migrations
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20190323_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now),
        ),
    ]
