# Generated by Django 2.1.7 on 2019-03-23 15:34

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20190323_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
    ]
