# Generated by Django 2.1.7 on 2019-03-23 15:35

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20190323_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_created=True),
        ),
    ]
