# Generated by Django 2.1.7 on 2019-03-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_results_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('nmec', models.CharField(max_length=100)),
            ],
        ),
    ]
