# Generated by Django 2.1.7 on 2019-03-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='nmec',
        ),
    ]
