# Generated by Django 2.1.7 on 2019-03-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_remove_answer_nmec'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='uid',
            field=models.CharField(default='00:00:00:00:00:00:00', max_length=100),
        ),
    ]
