# Generated by Django 2.1.7 on 2019-03-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_answer_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uid',
            field=models.CharField(default='00 00 00 00 00 00 00', max_length=100),
        ),
    ]
