# Generated by Django 2.1.7 on 2019-03-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20190329_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UID',
            new_name='Student',
        ),
    ]
