# Generated by Django 2.1.7 on 2019-04-03 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_remove_quiz_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
