# Generated by Django 2.1.7 on 2019-04-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20190403_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
