# Generated by Django 2.1.7 on 2019-04-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_auto_20190404_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='results',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Session'),
        ),
    ]
