# Generated by Django 2.1.7 on 2019-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_auto_20190404_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=100)),
            ],
        ),
    ]
