# Generated by Django 2.1.7 on 2019-04-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
