# Generated by Django 2.1.7 on 2019-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0043_auto_20190419_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='anonymous',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
