# Generated by Django 2.1.7 on 2019-04-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0045_results_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
