# Generated by Django 2.1.7 on 2019-05-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190502_1615'),
        ('quiz', '0048_auto_20190514_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
        ),
    ]
