# Generated by Django 2.1.7 on 2019-05-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
