# Generated by Django 2.1.7 on 2019-05-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_valid_ans'),
        ('quiz', '0050_remove_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(to='users.Course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='valid_ans',
            field=models.CharField(choices=[('First', 'First'), ('Last', 'Last')], default='Last', max_length=10),
        ),
    ]
