# Generated by Django 2.1.7 on 2019-05-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_auto_20190514_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=100)),
                ('right_ans', models.IntegerField()),
                ('wrong_ans', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Lesson')),
            ],
        ),
    ]
