# Generated by Django 2.1.7 on 2019-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_lessonstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstudent',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
    ]
